services:
  database:
    image: postgres:latest
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=store_db
    volumes:
      - db-data:/var/lib/postgresql/data

  app:
    build: 
      context: .
      dockerfile: dockerfile
    container_name: fashionmart_api
    ports:
      - 3000:3000
    depends_on:
      - database
      

volumes:
  db-data: