postgres:
  Port: 5432
  Host: localhost
  User: admin
  Password: admin
  Name: store_db

server:
  AppName: fashionmart-api
  Port: :3000
  Prefork: false
  Mode: Development

jwt:
  SecretKey: UwI3B03mFDV1gefDnCB0DQoFy9/rlZ8MNw4ksu2X1NzSSy9gcziNWxzsMKIZdGhn1DTEczB7YJ4uH3lfErTkaQ==

swagger:
  BasePath: /
  FilePath: ./docs/swagger.json
  Path: swagger
  title: swagger api doc

logger:
  Development: true
  DisableCaller: false
  DisableStacktrace: false
  Encoding: json
  Level: info
